version: "3.8"

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - embedg-local-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: process.env.userpost
      POSTGRES_DB: process.env.dbposto 
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3

  embedg:
    image: merlintor/embed-generator:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - EMBEDG_API__HOST=0.0.0.0
      - EMBEDG_POSTGRES__HOST=process.env.hostpostu
      - EMBEDG_POSTGRES__USER=process.env.userpost
      - EMBEDG_POSTGRES__DB=process.env.dbposto
      - EMBEDG_S3__ENDPOINT=minio:9000
    volumes:
      - ./config.yaml:/root/config.yaml

  minio:
    image: quay.io/minio/minio
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: embedg
      MINIO_ROOT_PASSWORD: 123456789
    volumes:
      - embedg-local-minio:/data

volumes:
  embedg-local-postgres:
  embedg-local-minio:
